In [2]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [8]:
# Importing the dataset
clean_credit_card_data = pd.read_csv('cleaned_credit_card_data_final.csv')

## 1) Decision Tree Classifier

Decision trees are a type of supervised learning algorithm that can be used for both classification and regression tasks. They work by splitting the data into subsets based on the value of input features, creating a tree-like structure where each node represents a feature and each branch represents a decision based on that feature.



In [11]:
# Importing necessary libraries for model building
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Selecting the target variable and features
X = clean_credit_card_data.drop(columns=['Credit_Score'])
y = clean_credit_card_data['Credit_Score']

# Encoding categorical variables if any
X = pd.get_dummies(X)

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(X_train, y_train)

# 5. Predict and evaluate
y_pred = decision_tree_model.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy:")
print(decision_tree_model.score(X_test, y_test))

Confusion Matrix:
[[  73    2    5    3]
 [   0 4486 1372    9]
 [   7 1316 8294  931]
 [   5   18  941 2538]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87        83
           1       0.77      0.76      0.77      5867
           2       0.78      0.79      0.78     10548
           3       0.73      0.72      0.73      3502

    accuracy                           0.77     20000
   macro avg       0.79      0.79      0.79     20000
weighted avg       0.77      0.77      0.77     20000

